### PR TITLE
Add a path check when finding extracts

### PR DESCRIPTION
**Pull request by shibdib**
Have found that this eliminates any pathing issues that extracting bots have with minimal overhead.

### CODE REVIEW

**Comment by dwesterwick** [comment]
@shibdib There's already a pathing check in `CountAllValidExfilsForBot`: `bot.Mover.CanGoToPoint(collider.transform.position, out Vector3 Destination, true)`. However, I've noticed that sometimes bots "extract" in weird locations far from the actual extract. ZB-014 in Woods is a good example. Are these the types of pathing issues you're experiencing? If so, I wonder if changing that line to something like `bot.Mover.CanGoToPoint(collider.transform.position, out Vector3 Destination, true, 2)` to define the max distance to the desired point would fix this. That would eliminate a redundant pathing check later on.

**Comment by dwesterwick** [comment]
Actually, I think that change might be necessary. In `ExtractAction`, the line to make the bot go to the extract is `NavMeshPathStatus pathStatus = BotOwner.Mover.GoToPoint(point, true, 0.5f, false, false);`. However, the minimum distance to the end of the path in my previous comment for `bot.Mover.CanGoToPoint(collider.transform.position, out Vector3 Destination, true)` is 10m. Therefore, it's a mismatch and can definitely cause issues. Maybe that additional parameter needs to be 0.5f instead of 2. 

@DrakiaXYZ This should probably be fixed for the next release. Maybe @shibdib can do some testing and see if this is another solution that works for this PR.

**Comment by dwesterwick** [comment]
After looking into this more, I was wrong. Unity's pathing is more fragile than I thought, so this extra check is still necessary even if a complete path was originally found for the extract position.

My original approach for the extract behavior was for bots to first make an attempt even if the path is incomplete and to recalculate it regularly as they follow it. If the path was still complete when they got to the end of it, then I had them give up and select another extract. However, this is probably a worse approach than @shibdib's because if a complete path isn't found, the bot is probably now much further away from all of the other extracts on the map and will have an even harder time successfully going to another one. 

@DrakiaXYZ, please merge @shibdib's PR! Sorry causing the long delay, @shibdib!

**Comment by shibdib** [comment]
All good, I'd been meaning to circle back to this but had put EFT projects on the back burner until 3.0.8 was out of BE.

**Comment by DrakiaXYZ** [comment]
Thanks @shibdib ! I've merged this :)

**Pull request merged**
